- name: "Terminate instances that were previously launched"
  local_action:
    module: ec2
    state: 'absent'
    instance_ids: '{{ ec2.instance_ids }}'
    region: '{{ region }}'
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
