- name: Build client instances
  ec2: instance_tags='{"Name":"http-stress-test"}'
       count="{{ instance_count }}"
       image="{{ image }}"
       instance_type="{{ instance_type }}"
       aws_access_key="{{ ec2_access_key }}"
       aws_secret_key="{{ ec2_secret_key }}"
       keypair="{{ keypair }}"
       region="{{ region }}"
       group="{{ group }}"
       wait=true
  register: ec2

- name: Add client instances to the group clients
  add_host: hostname={{ item.public_ip }} groupname=clients
  with_items: ec2.instances

- name: Wait for instances to listen on port 22
  wait_for:
    state=started
    host={{ item.public_dns_name }}
    port=22
  with_items: ec2.instances

